##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.17.1] date: [Tue Feb 07 22:39:38 CET 2023] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = BasicFreeRTOSDSP


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32g4xx_it.c \
Core/Src/stm32g4xx_hal_msp.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c \
Core/Src/system_stm32g4xx.c \
Core/Src/app_freertos.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
CMSIS/DSP/Source/BasicMathFunctions/arm_abs_f32.c       \
CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q15.c       \
CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q31.c       \
CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q7.c        \
CMSIS/DSP/Source/BasicMathFunctions/arm_add_f32.c       \
CMSIS/DSP/Source/BasicMathFunctions/arm_add_q15.c       \
CMSIS/DSP/Source/BasicMathFunctions/arm_add_q31.c       \
CMSIS/DSP/Source/BasicMathFunctions/arm_add_q7.c        \
CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_f32.c  \
CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q15.c  \
CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q31.c  \
CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q7.c   \
CMSIS/DSP/Source/BasicMathFunctions/arm_mult_f32.c      \
CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q15.c      \
CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q31.c      \
CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q7.c       \
CMSIS/DSP/Source/BasicMathFunctions/arm_negate_f32.c    \
CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q15.c    \
CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q31.c    \
CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q7.c     \
CMSIS/DSP/Source/BasicMathFunctions/arm_offset_f32.c    \
CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q15.c    \
CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q31.c    \
CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q7.c     \
CMSIS/DSP/Source/BasicMathFunctions/arm_scale_f32.c     \
CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q15.c     \
CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q31.c     \
CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q7.c      \
CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q15.c     \
CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q31.c     \
CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q7.c      \
CMSIS/DSP/Source/BasicMathFunctions/arm_sub_f32.c       \
CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q15.c       \
CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q31.c       \
CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q7.c        \
CMSIS/DSP/Source/BasicMathFunctions/basicMathFunctions.c \
CMSIS/DSP/Source/TransformFunctions/arm_bitreversal.c    \
CMSIS/DSP/Source/TransformFunctions/arm_bitreversal2.c   \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_f32.c       \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_q15.c       \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_q31.c       \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_f32.c\
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_init_f32.c \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_init_q15.c \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_init_q31.c \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_q15.c \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_q31.c \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_f32.c \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_init_f32.c \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_init_q15.c \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_init_q31.c \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_q15.c \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_q31.c \
CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix8_f32.c \
CMSIS/DSP/Source/TransformFunctions/arm_dct4_f32.c       \
CMSIS/DSP/Source/TransformFunctions/arm_dct4_init_f32.c  \
CMSIS/DSP/Source/TransformFunctions/arm_dct4_init_q15.c  \
CMSIS/DSP/Source/TransformFunctions/arm_dct4_init_q31.c  \
CMSIS/DSP/Source/TransformFunctions/arm_dct4_q15.c       \
CMSIS/DSP/Source/TransformFunctions/arm_dct4_q31.c       \
CMSIS/DSP/Source/TransformFunctions/arm_rfft_f32.c       \
CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_f32.c  \
CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_init_f32.c \
CMSIS/DSP/Source/TransformFunctions/arm_rfft_init_f32.c  \
CMSIS/DSP/Source/TransformFunctions/arm_rfft_init_q15.c  \
CMSIS/DSP/Source/TransformFunctions/arm_rfft_init_q31.c  \
CMSIS/DSP/Source/TransformFunctions/arm_rfft_q15.c       \
CMSIS/DSP/Source/TransformFunctions/arm_rfft_q31.c       \
CMSIS/DSP/Source/TransformFunctions/TransformFunctions.c \


# ASM sources
ASM_SOURCES =  \
startup_stm32g474xx.s \
CMSIS/DSP/Source/TransformFunctions/arm_bitreversal2.S


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32G474xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-I/usr/arm-none-eabi/include \
-ICore/Inc \
-IDrivers/STM32G4xx_HAL_Driver/Inc \
-IDrivers/STM32G4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32G4xx/Include \
-IDrivers/CMSIS/Include \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-IDrivers/CMSIS/DSP/Include \
-IDrivers/CMSIS/Core/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32G474RETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
